name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Change this if your index.html is in a folder

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
